<script lang="ts">
	// SvelteKit provides `enhance` — a Svelte action that intercepts form submissions
	// and uses fetch instead of a full page reload. After the server action runs,
	// it automatically re-runs the load() function so `data` stays fresh.
	import { enhance } from '$app/forms';
	// untrack() tells Svelte "read this reactive value once without subscribing to changes"
	// Used below to initialize local state from props without triggering the
	// "state_referenced_locally" warning — our intent is exactly a one-time snapshot.
	import { untrack } from 'svelte';

	// PageData is auto-generated by `svelte-kit sync` — it reflects the return
	// type of our load() function in +page.server.ts. Fully type-safe.
	import type { PageData } from './$types';

	import { areaFor, colorClasses } from '$lib/constants/areas';
	import { MVD_HINTS, ENERGY_LEVELS } from '$lib/constants/defaults';
	import { formatDateLong, formatTimeIST, getGreetingIST } from '$lib/utils/dates';
	import PomodoroTimer from '$lib/components/PomodoroTimer.svelte';

	// ── Health tips (9.3) — static rotation based on day of month ────────────
	const HEALTH_TIPS = [
		'Drink water before coffee. Your body is 8h dehydrated.',
		'Take a 5-min walk between focus blocks. Movement resets the mind.',
		'Stand up and stretch every 90 minutes.',
		'Sleep 7–8h. Cognitive performance drops 20% on less than 6h.',
		'Eat protein at breakfast — sustains energy better than carbs alone.',
		'Screen-off 30 min before bed. Blue light delays melatonin.',
		'Box breathing: 4s in · 4s hold · 4s out. Resets cortisol.'
	];
	const todayTip = HEALTH_TIPS[new Date().getDate() % HEALTH_TIPS.length];

	// Svelte 5: `$props()` replaces `export let data`.
	// The type annotation ensures `data` matches what our load() function returns.
	let { data }: { data: PageData } = $props();

	// ── Local UI state ────────────────────────────────────────────────────────
	// These are ephemeral input values — not persisted until a form is submitted.
	// $state() is Svelte 5's reactive primitive (replaces `let` with two-way binding).
	let newTaskText = $state('');
	let newTaskArea = $state(untrack(() => data.day.homeBase));
	let newInboxText = $state('');
	let showAddEvent = $state(false);
	let newEventTitle = $state('');
	let newEventTime = $state('');
	let newEventEndTime = $state('');
	let newEventArea = $state(untrack(() => data.day.homeBase));
	let newEventRemindOffset = $state('5'); // minutes before start

	// ── AI state (9.1, 9.5) ───────────────────────────────────────────────────
	let nlInput = $state('');
	let nlResult = $state('');
	let briefing = $state<{ briefing: string; suggestions: string[] } | null>(null);
	let briefingLoading = $state(false);

	// ── Derived values ────────────────────────────────────────────────────────
	// $derived() is Svelte 5's computed value (replaces $: reactive declarations).
	// Re-evaluates automatically when its dependencies change.
	const homeArea = $derived(areaFor(data.day.homeBase, data.areas));
	const homeAreaColors = $derived(homeArea ? colorClasses(homeArea.color) : null);
	const mvdHint = $derived(MVD_HINTS[data.day.homeBase] ?? 'Do one meaningful thing');
	const greeting = $derived(getGreetingIST());
	const dateLabel = $derived(formatDateLong(data.day.date));

	// Split tasks into pending (top) and completed (bottom, collapsible)
	const pendingTasks = $derived(data.tasks.filter((t) => !t.done));
	const doneTasks = $derived(data.tasks.filter((t) => t.done));

	async function fetchBriefing() {
		briefingLoading = true;
		briefing = null;
		try {
			const res = await fetch('/api/ai/briefing');
			briefing = await res.json();
		} catch {
			briefing = { briefing: 'Could not load briefing. Check your connection.', suggestions: [] };
		}
		briefingLoading = false;
	}
</script>

<div class="space-y-6">
	<!-- ── Header ──────────────────────────────────────────────────────────── -->
	<div class="flex items-start justify-between">
		<div>
			<p class="font-mono text-sm text-[#6b6b7a]">{greeting}</p>
			<h1 class="font-display text-2xl font-bold text-[#e2e2e8]">{dateLabel}</h1>
		</div>
		<!-- Today's home base area badge -->
		{#if homeArea && homeAreaColors}
			<span
				class="inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 font-mono text-xs {homeAreaColors.bg} {homeAreaColors.text}"
			>
				{homeArea.emoji}
				{homeArea.label}
			</span>
		{/if}
	</div>

	<!-- ── 9.5 Natural Language Input ──────────────────────────────────────── -->
	<!--
		Lets the user type anything — "review roadmap for Getfly", "meeting at 3pm tomorrow".
		Submitted to the nlTask server action which calls AI to parse and create the item.
	-->
	<form
		method="POST"
		action="?/nlTask"
		use:enhance={() => {
			return async ({ result, update }) => {
				await update({ reset: false });
				if (result.type === 'success' && result.data?.nlResult) {
					nlResult = result.data.nlResult as string;
					nlInput = '';
					setTimeout(() => (nlResult = ''), 4000);
				} else if (result.type === 'failure' && result.data?.nlResult) {
					nlResult = result.data.nlResult as string;
				}
			};
		}}
		class="flex flex-col gap-1"
	>
		<input type="hidden" name="dayId" value={data.day.id} />
		<div
			class="flex items-center gap-2 rounded-xl border border-[#1e1e2e] bg-[#161620] px-4 py-3
				focus-within:border-[#2a2a3e]"
		>
			<span class="font-mono text-sm text-[#6b6b7a]">✦</span>
			<input
				bind:value={nlInput}
				name="text"
				placeholder='Add anything... "review roadmap" or "meeting at 3pm"'
				class="flex-1 bg-transparent font-mono text-sm text-[#e2e2e8] placeholder-[#3a3a4e] outline-none"
			/>
			{#if nlInput}
				<button type="submit" class="font-mono text-xs text-[#6b6b7a] hover:text-[#e2e2e8]">
					↵
				</button>
			{/if}
		</div>
		{#if nlResult}
			<p class="pl-2 font-mono text-xs text-green-400">{nlResult}</p>
		{/if}
	</form>

	<!-- ── 9.1/9.2 AI Briefing ──────────────────────────────────────────────── -->
	<!--
		Lazy-loaded: only fetched when the user clicks "Generate".
		Avoids slowing down the initial page load.
	-->
	<div class="rounded-xl border border-[#1e1e2e] bg-[#161620] p-4">
		<div class="flex items-center justify-between">
			<p class="font-mono text-xs font-semibold uppercase tracking-wider text-[#6b6b7a]">
				AI Briefing
			</p>
			<button
				onclick={fetchBriefing}
				disabled={briefingLoading}
				class="font-mono text-xs text-[#6b6b7a] transition-colors hover:text-[#e2e2e8]
					disabled:opacity-40"
			>
				{briefingLoading ? 'Thinking…' : briefing ? 'Refresh' : 'Generate'}
			</button>
		</div>

		{#if briefing}
			<p class="mt-3 font-mono text-sm leading-relaxed text-[#e2e2e8]">{briefing.briefing}</p>
			{#if briefing.suggestions.length > 0}
				<ul class="mt-3 space-y-1">
					{#each briefing.suggestions as s}
						<li class="flex items-start gap-2 font-mono text-xs text-[#6b6b7a]">
							<span class="text-[#3a3a4e]">→</span>{s}
						</li>
					{/each}
				</ul>
			{/if}
		{:else if !briefingLoading}
			<p class="mt-2 font-mono text-xs text-[#3a3a4e]">
				Click Generate for a personalised briefing based on your tasks and energy.
			</p>
		{/if}
	</div>

	<!-- ── 9.3 Health Tip ───────────────────────────────────────────────────── -->
	<!-- Rotates daily based on day-of-month. Simple, no AI needed. -->
	<div class="flex items-start gap-3 rounded-xl border border-[#1e1e2e] bg-[#161620] px-4 py-3">
		<span class="mt-0.5 text-sm">💡</span>
		<p class="font-mono text-xs leading-relaxed text-[#6b6b7a]">{todayTip}</p>
	</div>

	<!-- ── Energy ────────────────────────────────────────────────────────────── -->
	<!-- Each button is its own <form> so a single click submits to ?/setEnergy -->
	<div class="rounded-xl border border-[#1e1e2e] bg-[#161620] p-4">
		<p class="mb-3 font-mono text-xs font-medium uppercase tracking-wider text-[#6b6b7a]">
			Energy
		</p>
		<div class="flex gap-2">
			{#each ENERGY_LEVELS as level}
				<form method="POST" action="?/setEnergy" use:enhance>
					<input type="hidden" name="dayId" value={data.day.id} />
					<input type="hidden" name="energy" value={level.key} />
					<button
						type="submit"
						title={level.label}
						class="flex flex-col items-center gap-1 rounded-lg px-3 py-2 text-xl transition-colors
						       {data.day.energy === level.key
							? 'bg-purple-500/20 ring-1 ring-purple-500'
							: 'bg-[#0c0c0f] hover:bg-[#1e1e2e]'}"
					>
						{level.emoji}
						<span
							class="font-mono text-xs {data.day.energy === level.key
								? 'text-purple-400'
								: 'text-[#6b6b7a]'}">{level.label}</span
						>
					</button>
				</form>
			{/each}
		</div>
	</div>

	<!-- ── MVD Card ──────────────────────────────────────────────────────────── -->
	<!-- MVD = Minimum Viable Day. One checkbox — is today a win? -->
	<div
		class="rounded-xl border p-4 transition-colors {data.day.mvdDone
			? 'border-green-500/40 bg-green-500/5'
			: 'border-[#1e1e2e] bg-[#161620]'}"
	>
		<form method="POST" action="?/toggleMvd" use:enhance class="flex items-start gap-3">
			<input type="hidden" name="dayId" value={data.day.id} />
			<input type="hidden" name="current" value={String(data.day.mvdDone)} />
			<!-- Checkbox button — visually represents done/not-done state -->
			<button
				type="submit"
				class="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded border-2 transition-colors
				       {data.day.mvdDone
					? 'border-green-500 bg-green-500'
					: 'border-[#3e3e4e] hover:border-green-500'}"
			>
				{#if data.day.mvdDone}
					<!-- Checkmark SVG — inline so no image request -->
					<svg viewBox="0 0 12 12" fill="none" class="h-3 w-3">
						<path
							d="M2 6l3 3 5-5"
							stroke="white"
							stroke-width="1.5"
							stroke-linecap="round"
							stroke-linejoin="round"
						/>
					</svg>
				{/if}
			</button>
			<div>
				<p class="font-mono text-xs uppercase tracking-wider text-[#6b6b7a]">
					Minimum Viable Day
				</p>
				<p
					class="font-mono text-sm {data.day.mvdDone
						? 'text-green-400 line-through'
						: 'text-[#e2e2e8]'}"
				>
					{mvdHint}
				</p>
			</div>
		</form>
	</div>

	<!-- ── Schedule / Events ─────────────────────────────────────────────────── -->
	<div class="space-y-2">
		<div class="flex items-center justify-between">
			<h2 class="font-display text-sm font-semibold uppercase tracking-wider text-[#e2e2e8]">
				Schedule
			</h2>
			<!-- Toggle the add-event form — plain JS, no server round-trip needed -->
			<button
				onclick={() => (showAddEvent = !showAddEvent)}
				class="font-mono text-xs text-purple-400 transition-colors hover:text-purple-300"
			>
				{showAddEvent ? '✕ cancel' : '+ add event'}
			</button>
		</div>

		{#if data.events.length === 0 && !showAddEvent}
			<p class="py-1 font-mono text-xs text-[#6b6b7a]">No events today</p>
		{/if}

		{#each data.events as event}
			{@const evArea = event.area ? areaFor(event.area, data.areas) : null}
			{@const evColors = evArea ? colorClasses(evArea.color) : null}
			<div
				class="flex items-center gap-3 rounded-lg border border-[#1e1e2e] bg-[#161620] px-3 py-2.5"
			>
				<!-- Time in IST — startsAt comes from DB as Date via SvelteKit devalue -->
				<!-- Show "HH:MM" or "HH:MM → HH:MM" when end time is set -->
				<span class="shrink-0 font-mono text-sm font-medium text-purple-400">
					{formatTimeIST(event.startsAt)}{event.endsAt ? " → " + formatTimeIST(event.endsAt) : ""}
				</span>
				<span class="flex-1 font-mono text-sm text-[#e2e2e8]">{event.title}</span>
				{#if evArea && evColors}
					<span
						class="rounded px-1.5 py-0.5 font-mono text-xs {evColors.bg} {evColors.text}"
					>
						{evArea.emoji}
					</span>
				{/if}
				<form method="POST" action="?/deleteEvent" use:enhance>
					<input type="hidden" name="id" value={event.id} />
					<button
						type="submit"
						class="font-mono text-xs text-[#3e3e4e] transition-colors hover:text-red-400"
					>
						✕
					</button>
				</form>
			</div>
		{/each}

		{#if showAddEvent}
			<!-- Add event form — closes and resets on successful submit -->
			<form
				method="POST"
				action="?/addEvent"
				use:enhance={() => {
					return async ({ update }) => {
						await update(); // re-runs load() to refresh events list
						showAddEvent = false;
						newEventTitle = '';
						newEventTime = '';
						newEventEndTime = '';
						newEventRemindOffset = '5';
					};
				}}
				class="space-y-2 rounded-lg border border-[#1e1e2e] bg-[#161620] p-3"
			>
				<input type="hidden" name="dayId" value={data.day.id} />
				<input
					bind:value={newEventTitle}
					name="title"
					required
					placeholder="Event title..."
					class="w-full bg-transparent font-mono text-sm text-[#e2e2e8] placeholder-[#3e3e4e] outline-none"
				/>
				<!-- Row 1: start time → optional end time -->
				<div class="flex items-center gap-2">
					<!-- datetime-local input — user picks in IST, server converts to UTC -->
					<input
						bind:value={newEventTime}
						type="datetime-local"
						name="startsAt"
						required
						placeholder="Start time"
						class="flex-1 rounded border border-[#1e1e2e] bg-[#0c0c0f] px-2 py-1 font-mono text-xs text-[#e2e2e8] outline-none"
					/>
					<span class="font-mono text-xs text-[#3e3e4e]">→</span>
					<!-- Optional end time — empty = no end time saved -->
					<input
						bind:value={newEventEndTime}
						type="datetime-local"
						name="endsAt"
						placeholder="End time (optional)"
						class="flex-1 rounded border border-[#1e1e2e] bg-[#0c0c0f] px-2 py-1 font-mono text-xs text-[#e2e2e8] outline-none"
					/>
				</div>
				<!-- Row 2: area, remind offset, submit -->
				<div class="flex items-center gap-2">
					<select
						bind:value={newEventArea}
						name="area"
						class="rounded border border-[#1e1e2e] bg-[#0c0c0f] px-2 py-1 font-mono text-xs text-[#e2e2e8] outline-none"
					>
						<option value="">No area</option>
						{#each data.areas.filter(a => !a.suspended) as area}
							<option value={area.key}>{area.emoji} {area.label}</option>
						{/each}
					</select>
					<!-- How many minutes before the event to send the Telegram reminder -->
					<select
						bind:value={newEventRemindOffset}
						name="remindOffset"
						class="rounded border border-[#1e1e2e] bg-[#0c0c0f] px-2 py-1 font-mono text-xs text-[#e2e2e8] outline-none"
					>
						<option value="0">At event time</option>
						<option value="5">5 min before</option>
						<option value="10">10 min before</option>
						<option value="15">15 min before</option>
						<option value="30">30 min before</option>
						<option value="60">1 hr before</option>
					</select>
					<button
						type="submit"
						class="rounded bg-purple-500/20 px-3 py-1 font-mono text-xs text-purple-400 transition-colors hover:bg-purple-500/30"
					>
						Add
					</button>
				</div>
			</form>
		{/if}
	</div>

	<!-- ── Tasks ─────────────────────────────────────────────────────────────── -->
	<div class="space-y-2">
		<h2 class="font-display text-sm font-semibold uppercase tracking-wider text-[#e2e2e8]">
			Tasks
		</h2>

		<!-- Pending tasks -->
		{#each pendingTasks as task}
			{@const taskArea = task.area ? areaFor(task.area, data.areas) : null}
			{@const taskColors = taskArea ? colorClasses(taskArea.color) : null}
			<div
				class="flex items-center gap-3 rounded-lg border border-[#1e1e2e] bg-[#161620] px-3 py-2.5"
			>
				<form method="POST" action="?/toggleTask" use:enhance>
					<input type="hidden" name="id" value={task.id} />
					<input type="hidden" name="done" value={String(task.done)} />
					<button
						type="submit"
						aria-label="Mark as done"
						class="h-4 w-4 shrink-0 rounded border-2 border-[#3e3e4e] transition-colors hover:border-purple-500"
					></button>
				</form>
				<span class="flex-1 font-mono text-sm text-[#e2e2e8]">{task.text}</span>
				{#if taskArea && taskColors}
					<span
						class="rounded px-1.5 py-0.5 font-mono text-xs {taskColors.bg} {taskColors.text}"
					>
						{taskArea.emoji}
					</span>
				{/if}
				<form method="POST" action="?/deleteTask" use:enhance>
					<input type="hidden" name="id" value={task.id} />
					<button
						type="submit"
						class="font-mono text-xs text-[#3e3e4e] transition-colors hover:text-red-400"
					>
						✕
					</button>
				</form>
			</div>
		{/each}

		<!-- Add task inline form — pressing Enter submits -->
		<form
			method="POST"
			action="?/addTask"
			use:enhance={() => {
				return async ({ update }) => {
					await update();
					newTaskText = ''; // clear the input after successful add
				};
			}}
			class="flex items-center gap-2 rounded-lg border border-[#1e1e2e] bg-[#161620] px-3 py-2.5"
		>
			<input type="hidden" name="dayId" value={data.day.id} />
			<span class="font-mono text-[#3e3e4e]">+</span>
			<input
				bind:value={newTaskText}
				name="text"
				required
				placeholder="Add a task..."
				class="flex-1 bg-transparent font-mono text-sm text-[#e2e2e8] placeholder-[#3e3e4e] outline-none"
			/>
			<select
				bind:value={newTaskArea}
				name="area"
				class="rounded border border-[#1e1e2e] bg-[#0c0c0f] px-2 py-1 font-mono text-xs text-[#e2e2e8] outline-none"
			>
				<option value="">No area</option>
				{#each data.areas.filter(a => !a.suspended) as area}
					<option value={area.key}>{area.emoji} {area.label}</option>
				{/each}
			</select>
		</form>

		<!-- Completed tasks — collapsed by default to keep things clean -->
		{#if doneTasks.length > 0}
			<details class="group">
				<!-- list-none removes the default triangle from <summary> -->
				<summary
					class="flex cursor-pointer list-none items-center gap-1.5 py-1 font-mono text-xs text-[#6b6b7a] transition-colors hover:text-[#e2e2e8]"
				>
					<!-- Rotate arrow on open — `group-open:` targets the open state of parent <details> -->
					<span class="inline-block transition-transform group-open:rotate-90">▶</span>
					{doneTasks.length} completed
				</summary>
				<div class="mt-1 space-y-1">
					{#each doneTasks as task}
						{@const taskArea = task.area ? areaFor(task.area, data.areas) : null}
						{@const taskColors = taskArea ? colorClasses(taskArea.color) : null}
						<div
							class="flex items-center gap-3 rounded-lg border border-[#1e1e2e]/50 bg-[#161620]/50 px-3 py-2"
						>
							<form method="POST" action="?/toggleTask" use:enhance>
								<input type="hidden" name="id" value={task.id} />
								<input type="hidden" name="done" value={String(task.done)} />
								<button
									type="submit"
									aria-label="Mark as not done"
									class="flex h-4 w-4 shrink-0 items-center justify-center rounded border-2 border-green-500/50 bg-green-500/10 transition-colors"
								>
									<svg viewBox="0 0 12 12" fill="none" class="h-2.5 w-2.5">
										<path
											d="M2 6l3 3 5-5"
											stroke="rgb(74 222 128)"
											stroke-width="1.5"
											stroke-linecap="round"
											stroke-linejoin="round"
										/>
									</svg>
								</button>
							</form>
							<span class="flex-1 font-mono text-sm text-[#6b6b7a] line-through"
								>{task.text}</span
							>
							{#if taskArea && taskColors}
								<span
									class="rounded px-1.5 py-0.5 font-mono text-xs opacity-50 {taskColors.bg} {taskColors.text}"
								>
									{taskArea.emoji}
								</span>
							{/if}
							<form method="POST" action="?/deleteTask" use:enhance>
								<input type="hidden" name="id" value={task.id} />
								<button
									type="submit"
									class="font-mono text-xs text-[#3e3e4e] transition-colors hover:text-red-400"
								>
									✕
								</button>
							</form>
						</div>
					{/each}
				</div>
			</details>
		{/if}
	</div>

	<!-- ── Pomodoro Timer ────────────────────────────────────────────────────── -->
	<PomodoroTimer dayId={data.day.id} sessions={data.day.pomodoroSessions} />

	<!-- ── Brain Dump / Inbox ─────────────────────────────────────────────────── -->
	<!-- Quick capture for anything on your mind — not tied to a specific time or task -->
	<div class="space-y-2">
		<h2 class="font-display text-sm font-semibold uppercase tracking-wider text-[#e2e2e8]">
			Brain Dump
		</h2>

		<!-- Capture form — pressing Enter submits -->
		<form
			method="POST"
			action="?/addInboxItem"
			use:enhance={() => {
				return async ({ update }) => {
					await update();
					newInboxText = '';
				};
			}}
			class="flex items-center gap-2 rounded-lg border border-[#1e1e2e] bg-[#161620] px-3 py-2.5"
		>
			<span class="font-mono text-[#3e3e4e]">⚡</span>
			<input
				bind:value={newInboxText}
				name="text"
				placeholder="Dump it out..."
				class="flex-1 bg-transparent font-mono text-sm text-[#e2e2e8] placeholder-[#3e3e4e] outline-none"
			/>
		</form>

		{#each data.inboxItems as item}
			<div
				class="flex items-center gap-2 rounded-lg border border-[#1e1e2e] bg-[#161620] px-3 py-2"
			>
				<span class="flex-1 font-mono text-sm text-[#e2e2e8]">{item.text}</span>

				<!-- Convert inbox item to a task for today -->
				<form method="POST" action="?/convertInboxToTask" use:enhance>
					<input type="hidden" name="itemId" value={item.id} />
					<input type="hidden" name="text" value={item.text} />
					<input type="hidden" name="dayId" value={data.day.id} />
					<button
						type="submit"
						title="Convert to task"
						class="px-1 font-mono text-xs text-[#6b6b7a] transition-colors hover:text-purple-400"
					>
						→ task
					</button>
				</form>

				<form method="POST" action="?/deleteInboxItem" use:enhance>
					<input type="hidden" name="id" value={item.id} />
					<button
						type="submit"
						class="font-mono text-xs text-[#3e3e4e] transition-colors hover:text-red-400"
					>
						✕
					</button>
				</form>
			</div>
		{/each}
	</div>

	<!-- ── Daily Note ─────────────────────────────────────────────────────────── -->
	<!-- Free-form text. Auto-saves when you click/tab away (onblur). -->
	<div class="space-y-2">
		<h2 class="font-display text-sm font-semibold uppercase tracking-wider text-[#e2e2e8]">
			Note
		</h2>
		<form method="POST" action="?/updateNote" use:enhance>
			<input type="hidden" name="dayId" value={data.day.id} />
			<!-- requestSubmit() is the modern way to programmatically submit — it triggers form validation -->
			<textarea
				name="note"
				placeholder="How's the day going? Reflections, thoughts, blockers..."
				onblur={(e) => e.currentTarget.form?.requestSubmit()}
				class="min-h-[100px] w-full resize-none rounded-lg border border-[#1e1e2e] bg-[#161620] p-3
				       font-mono text-sm text-[#e2e2e8] placeholder-[#3e3e4e] outline-none
				       transition-colors focus:border-purple-500/50"
			>{data.day.note}</textarea>
		</form>
	</div>
</div>
