<script lang="ts">
	// SvelteKit provides `enhance` — a Svelte action that intercepts form submissions
	// and uses fetch instead of a full page reload. After the server action runs,
	// it automatically re-runs the load() function so `data` stays fresh.
	import { enhance } from '$app/forms';
	// untrack() tells Svelte "read this reactive value once without subscribing to changes"
	// Used below to initialize local state from props without triggering the
	// "state_referenced_locally" warning — our intent is exactly a one-time snapshot.
	import { untrack } from 'svelte';

	// PageData is auto-generated by `svelte-kit sync` — it reflects the return
	// type of our load() function in +page.server.ts. Fully type-safe.
	import type { PageData } from './$types';

	import { areaFor, colorClasses } from '$lib/constants/areas';
	import { MVD_HINTS, ENERGY_LEVELS } from '$lib/constants/defaults';
	import { formatDateLong, formatTimeIST, getGreetingIST } from '$lib/utils/dates';
	import PanelCard from '$lib/components/PanelCard.svelte';
	import PomodoroTimer from '$lib/components/PomodoroTimer.svelte';
	import TwoColumnPage from '$lib/components/TwoColumnPage.svelte';

	// Svelte 5: `$props()` replaces `export let data`.
	// The type annotation ensures `data` matches what our load() function returns.
	let { data }: { data: PageData } = $props();

	// ── Local UI state ────────────────────────────────────────────────────────
	// These are ephemeral input values — not persisted until a form is submitted.
	// $state() is Svelte 5's reactive primitive (replaces `let` with two-way binding).
	let newTaskText = $state('');
	let newTaskArea = $state(untrack(() => data.day.homeBase));
	let newInboxText = $state('');
	let showAddEvent = $state(false);
	let newEventTitle = $state('');
	let newEventTime = $state('');
	let newEventEndTime = $state('');
	let newEventArea = $state(untrack(() => data.day.homeBase));
	let newEventRemindOffset = $state('5'); // minutes before start

	// ── Recurring events UI state ─────────────────────────────────────────────
	let showManageRecurring = $state(false);
	let showAddRecurring = $state(false);
	const WEEKDAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
	let newRecurringDays = $state<string[]>([]);

	// ── Sleep state ───────────────────────────────────────────────────────────
	// Pre-populated from DB if sleep was logged previously (converts UTC → IST HH:MM)
	let bedTime = $state(data.day.sleepStart ? formatTimeIST(data.day.sleepStart) : '');
	let wakeTime = $state(data.day.sleepEnd ? formatTimeIST(data.day.sleepEnd) : '');

	// Derived sleep duration for display (bed is "yesterday", wake is "today")
	const sleepDuration = $derived(() => {
		if (!bedTime || !wakeTime) return null;
		const [bedH, bedM] = bedTime.split(':').map(Number);
		const [wakeH, wakeM] = wakeTime.split(':').map(Number);
		const bedMins = bedH * 60 + bedM;
		const wakeMins = wakeH * 60 + wakeM;
		// Sleep crosses midnight, so add 24h worth of minutes to wake
		const durationMins = (wakeMins + 24 * 60 - bedMins) % (24 * 60);
		return { hours: Math.floor(durationMins / 60), mins: durationMins % 60 };
	});

	// ── AI state (9.1, 9.5) ───────────────────────────────────────────────────
	let nlInput = $state('');
	let nlResult = $state('');
	let briefing = $state<{ briefing: string; suggestions: string[] } | null>(null);
	let briefingLoading = $state(false);

	// ── New state for briefing collapse and live clock ─────────────────────────
	let briefingCollapsed = $state(false);
	let now = $state(new Date());

	// Live clock — updates every 30 seconds for ACTIVE event detection
	// $effect runs after mount and cleans up on destroy
	$effect(() => {
		const interval = setInterval(() => {
			now = new Date();
		}, 30_000);
		return () => clearInterval(interval);
	});

	// ── Briefing text renderer — parses [hl]...[/hl] and [area:key]...[/area] markers ──
	// Returns HTML string safe to use with {@html ...}
	function renderBriefing(text: string, areas: typeof data.areas): string {
		// Replace [area:key]...[/area] with area-colored spans
		let result = text.replace(/\[area:([^\]]+)\](.*?)\[\/area\]/g, (_, key, content) => {
			const area = areas.find(a => a.key === key);
			if (!area) return content;
			// Map color key to a Tailwind inline hex — using a simple lookup
			const colorMap: Record<string, string> = {
				blue: '#60a5fa', purple: '#c084fc', green: '#4ade80',
				orange: '#fb923c', rose: '#fb7185', amber: '#fbbf24',
				teal: '#2dd4bf', pink: '#f472b6', red: '#f87171', indigo: '#818cf8'
			};
			const hex = colorMap[area.color] ?? '#c084fc';
			return `<span style="color:${hex}">${content}</span>`;
		});

		// Replace [hl]...[/hl] with accent-colored spans
		result = result.replace(/\[hl\](.*?)\[\/hl\]/g,
			'<span class="text-violet-400 font-medium">$1</span>'
		);

		return result;
	}

	// ── Derived values ────────────────────────────────────────────────────────
	// $derived() is Svelte 5's computed value (replaces $: reactive declarations).
	// Re-evaluates automatically when its dependencies change.
	const homeArea = $derived(areaFor(data.day.homeBase, data.areas));
	const homeAreaColors = $derived(homeArea ? colorClasses(homeArea.color) : null);
	const mvdHint = $derived(MVD_HINTS[data.day.homeBase] ?? 'Do one meaningful thing');
	const greeting = $derived(getGreetingIST());
	const dateLabel = $derived(formatDateLong(data.day.date));

	// Split tasks into pending (top) and completed (bottom, collapsible)
	const pendingTasks = $derived(data.tasks.filter((t) => !t.done));
	const doneTasks = $derived(data.tasks.filter((t) => t.done));

	async function fetchBriefing() {
		briefingLoading = true;
		briefing = null;
		try {
			const res = await fetch('/api/ai/briefing');
			briefing = await res.json();
		} catch {
			briefing = { briefing: 'Could not load briefing. Check your connection.', suggestions: [] };
		}
		briefingLoading = false;
	}
</script>

<TwoColumnPage>
  {#snippet main()}
	<!-- ── Header ──────────────────────────────────────────────────────────── -->
	<div class="flex items-start justify-between">
		<div>
			<p class="font-mono text-sm text-[#6b6b7a]">{greeting}</p>
			<h1 class="font-display text-2xl font-bold text-[#e2e2e8]">{dateLabel}</h1>
		</div>
		<!-- Today's home base area badge -->
		{#if homeArea && homeAreaColors}
			<span
				class="inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 font-mono text-xs {homeAreaColors.bg} {homeAreaColors.text}"
			>
				{homeArea.emoji}
				{homeArea.label}
			</span>
		{/if}
	</div>

	<!-- ── Command Bar ──────────────────────────────────────────────────────── -->
	<form
		method="POST"
		action="?/nlTask"
		use:enhance={() => {
			return async ({ result, update }) => {
				await update({ reset: false });
				if (result.type === 'success' && result.data?.nlResult) {
					nlResult = result.data.nlResult as string;
					nlInput = '';
					setTimeout(() => (nlResult = ''), 4000);
				} else if (result.type === 'failure' && result.data?.nlResult) {
					nlResult = result.data.nlResult as string;
				}
			};
		}}
		class="flex flex-col gap-1"
	>
		<input type="hidden" name="dayId" value={data.day.id} />
		<div
			class="flex items-center gap-3 rounded-lg border border-[#1e1e2e] bg-[#161620] px-4 py-3
				   focus-within:border-[#2a2a3e]"
		>
			<!-- ⌘ command symbol prefix -->
			<span class="shrink-0 font-mono text-sm text-[#3a3a4e]">⌘</span>
			<input
				bind:value={nlInput}
				name="text"
				placeholder="Review roadmap or meeting at 3pm..."
				class="flex-1 bg-transparent font-mono text-sm text-[#e2e2e8] placeholder-[#3a3a4e] outline-none"
			/>
			<!-- ENTER button — always visible -->
			<button
				type="submit"
				class="shrink-0 rounded border border-[#2a2a3e] px-2 py-0.5 font-mono text-[10px]
					   uppercase tracking-widest text-[#6b6b7a] transition-colors hover:border-[#3a3a4e]
					   hover:text-[#e2e2e8]"
			>
				Enter
			</button>
		</div>
		{#if nlResult}
			<p class="pl-2 font-mono text-xs text-green-400">{nlResult}</p>
		{/if}
	</form>

	<!-- ── Cognitive Briefing ────────────────────────────────────────────────── -->
	<div class="rounded-lg border border-[#1e1e2e] bg-[#161620] p-4">
		<div class="flex items-center justify-between">
			<div class="flex items-center gap-2">
				<!-- Spark icon -->
				<svg width="12" height="12" viewBox="0 0 12 12" fill="none" class="text-violet-400">
					<path d="M6 1L7.5 4.5L11 6L7.5 7.5L6 11L4.5 7.5L1 6L4.5 4.5L6 1Z" fill="currentColor"/>
				</svg>
				<span class="font-mono text-[10px] font-semibold uppercase tracking-[0.12em] text-[#6b6b7a]">
					Cognitive Briefing
				</span>
			</div>
			<div class="flex items-center gap-3">
				<button
					onclick={fetchBriefing}
					disabled={briefingLoading}
					class="font-mono text-[10px] text-[#6b6b7a] transition-colors hover:text-[#e2e2e8] disabled:opacity-40"
				>
					{briefingLoading ? 'Thinking…' : briefing ? '↺ Refresh' : 'Generate'}
				</button>
				<!-- Collapse chevron — toggles briefing visibility -->
				{#if briefing}
					<button
						onclick={() => (briefingCollapsed = !briefingCollapsed)}
						class="text-[#3a3a4e] transition-colors hover:text-[#6b6b7a]"
						aria-label="Toggle briefing"
					>
						<svg width="12" height="12" viewBox="0 0 12 12" fill="none">
							<path
								d={briefingCollapsed ? 'M3 4.5L6 7.5L9 4.5' : 'M3 7.5L6 4.5L9 7.5'}
								stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"
							/>
						</svg>
					</button>
				{/if}
			</div>
		</div>

		{#if briefing && !briefingCollapsed}
			<!-- Briefing text with inline highlights parsed from [hl] and [area:key] markers -->
			<p class="mt-3 font-mono text-sm leading-relaxed text-[#c8c8d4]">
				{@html renderBriefing(briefing.briefing, data.areas)}
			</p>

			<!-- Action buttons -->
			<div class="mt-4 flex flex-wrap gap-2">
				<button
					type="button"
					class="flex items-center gap-1.5 rounded border border-[#2a2a3e] px-3 py-1.5
						   font-mono text-[10px] uppercase tracking-widest text-[#6b6b7a]
						   transition-colors hover:border-[#3a3a4e] hover:text-[#e2e2e8]"
				>
					<!-- Calendar icon -->
					<svg width="10" height="10" viewBox="0 0 10 10" fill="none">
						<rect x="1" y="2" width="8" height="7" rx="1" stroke="currentColor" stroke-width="1.2"/>
						<path d="M1 4.5H9" stroke="currentColor" stroke-width="1.2"/>
						<path d="M3 1V3M7 1V3" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"/>
					</svg>
					Reschedule Low Priority
				</button>
				<button
					type="button"
					onclick={() => {
						// Scroll to pomodoro timer in the panel
						document.getElementById('pomodoro-panel')?.scrollIntoView({ behavior: 'smooth' });
					}}
					class="flex items-center gap-1.5 rounded border border-[#2a2a3e] px-3 py-1.5
						   font-mono text-[10px] uppercase tracking-widest text-[#6b6b7a]
						   transition-colors hover:border-violet-500/50 hover:text-violet-400"
				>
					<!-- Timer icon -->
					<svg width="10" height="10" viewBox="0 0 10 10" fill="none">
						<circle cx="5" cy="5.5" r="3.5" stroke="currentColor" stroke-width="1.2"/>
						<path d="M5 3.5V5.5L6.5 6.5" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"/>
						<path d="M3.5 1H6.5" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"/>
					</svg>
					Start Focus Session
				</button>
			</div>
		{:else if !briefingLoading && !briefing}
			<p class="mt-2 font-mono text-xs text-[#3a3a4e]">
				Generate a personalised briefing based on your tasks and energy.
			</p>
		{/if}
	</div>

	<!-- ── Schedule ─────────────────────────────────────────────────────────── -->
	<div class="space-y-1">
		<!-- Header row -->
		<div class="flex items-center justify-between py-1">
			<span class="font-mono text-[10px] font-semibold uppercase tracking-[0.12em] text-[#6b6b7a]">
				Schedule
			</span>
			<span class="font-mono text-[10px] text-[#3a3a4e]">
				{data.user?.workdayStart ?? '09:00'} — {data.user?.workdayEnd ?? '18:00'}
			</span>
		</div>

		{#if data.events.length === 0 && !showAddEvent}
			<p class="py-1 font-mono text-xs text-[#3a3a4e]">No events — add one below</p>
		{/if}

		{#each data.events as event}
			{@const evArea = event.area ? areaFor(event.area, data.areas) : null}
			{@const evColors = evArea ? colorClasses(evArea.color) : null}
			{@const isActive = now >= event.startsAt && (!event.endsAt || now <= event.endsAt)}
			<div
				class="flex items-center gap-3 rounded-lg px-3 py-2.5 transition-colors
					   {isActive ? 'bg-[#1e1e2e] border border-[#2a2a3e]' : 'bg-[#161620] border border-[#1e1e2e]'}"
			>
				<!-- Time -->
				<span class="w-10 shrink-0 font-mono text-xs text-[#6b6b7a]">
					{formatTimeIST(event.startsAt)}
				</span>
				<!-- Area color dot -->
				{#if evArea && evColors}
					<span class="h-1.5 w-1.5 shrink-0 rounded-full {evColors.solid}"></span>
				{:else}
					<span class="h-1.5 w-1.5 shrink-0 rounded-full bg-[#3a3a4e]"></span>
				{/if}
				<!-- Title -->
				<span class="flex-1 font-mono text-sm {isActive ? 'text-[#e2e2e8]' : 'text-[#c8c8d4]'}">
					{event.title}
				</span>
				<!-- ACTIVE badge -->
				{#if isActive}
					<span class="rounded px-1.5 py-0.5 font-mono text-[9px] font-semibold uppercase
								 tracking-widest bg-violet-500/10 text-violet-400">
						Active
					</span>
				{/if}
				<!-- Recurring badge -->
				{#if event.recurringEventId}
					<span title="Recurring event" class="font-mono text-[10px] text-[#3a3a4e]">↻</span>
				{/if}
				<!-- Delete -->
				<form method="POST" action="?/deleteEvent" use:enhance>
					<input type="hidden" name="id" value={event.id} />
					<button type="submit" class="font-mono text-[10px] text-[#3e3e4e] transition-colors hover:text-red-400">
						✕
					</button>
				</form>
			</div>
		{/each}

		<!-- Add event row -->
		{#if !showAddEvent}
			<button
				onclick={() => (showAddEvent = true)}
				class="flex items-center gap-2 py-1.5 font-mono text-xs text-[#3a3a4e]
					   transition-colors hover:text-[#6b6b7a]"
			>
				<span class="text-base leading-none">+</span>
				<span>Add Event</span>
			</button>
		{:else}
			<!-- Add event form -->
			<form
				method="POST"
				action="?/addEvent"
				use:enhance={() => {
					return async ({ update }) => {
						await update();
						showAddEvent = false;
						newEventTitle = '';
						newEventTime = '';
						newEventEndTime = '';
						newEventRemindOffset = '5';
					};
				}}
				class="space-y-2 rounded-lg border border-[#1e1e2e] bg-[#161620] p-3"
			>
				<input type="hidden" name="dayId" value={data.day.id} />
				<input
					bind:value={newEventTitle}
					name="title"
					required
					placeholder="Event title..."
					class="w-full bg-transparent font-mono text-sm text-[#e2e2e8] placeholder-[#3e3e4e] outline-none"
				/>
				<div class="flex items-center gap-2">
					<input
						bind:value={newEventTime}
						type="datetime-local"
						name="startsAt"
						required
						class="flex-1 rounded border border-[#1e1e2e] bg-[#0c0c0f] px-2 py-1 font-mono text-xs text-[#e2e2e8] outline-none"
					/>
					<span class="font-mono text-xs text-[#3e3e4e]">→</span>
					<input
						bind:value={newEventEndTime}
						type="datetime-local"
						name="endsAt"
						class="flex-1 rounded border border-[#1e1e2e] bg-[#0c0c0f] px-2 py-1 font-mono text-xs text-[#e2e2e8] outline-none"
					/>
				</div>
				<div class="flex items-center gap-2">
					<select
						bind:value={newEventArea}
						name="area"
						class="rounded border border-[#1e1e2e] bg-[#0c0c0f] px-2 py-1 font-mono text-xs text-[#e2e2e8] outline-none"
					>
						<option value="">No area</option>
						{#each data.areas.filter(a => !a.suspended) as area}
							<option value={area.key}>{area.emoji} {area.label}</option>
						{/each}
					</select>
					<select
						bind:value={newEventRemindOffset}
						name="remindOffset"
						class="rounded border border-[#1e1e2e] bg-[#0c0c0f] px-2 py-1 font-mono text-xs text-[#e2e2e8] outline-none"
					>
						<option value="0">At event time</option>
						<option value="5">5 min before</option>
						<option value="10">10 min before</option>
						<option value="15">15 min before</option>
						<option value="30">30 min before</option>
						<option value="60">1 hr before</option>
					</select>
					<button
						type="submit"
						class="rounded bg-violet-500/20 px-3 py-1 font-mono text-xs text-violet-400 transition-colors hover:bg-violet-500/30"
					>
						Add
					</button>
					<button
						type="button"
						onclick={() => (showAddEvent = false)}
						class="font-mono text-xs text-[#3e3e4e] transition-colors hover:text-[#6b6b7a]"
					>
						✕
					</button>
				</div>
			</form>
		{/if}
	</div>

	<!-- ── Manage Recurring Events ──────────────────────────────────────────── -->
	<!--
		Collapsible section for creating and deleting recurring event templates.
		Instances are auto-created by load() each day — this is just the config panel.
	-->
	<div class="space-y-1">
		<button
			onclick={() => (showManageRecurring = !showManageRecurring)}
			class="flex items-center gap-1.5 font-mono text-[10px] text-[#3a3a4e] transition-colors hover:text-[#6b6b7a]"
		>
			<span>↻</span>
			<span>Manage recurring ({data.recurringTemplates.length})</span>
			<svg width="8" height="8" viewBox="0 0 8 8" fill="none">
				<path
					d={showManageRecurring ? 'M1 5L4 2L7 5' : 'M1 3L4 6L7 3'}
					stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"
				/>
			</svg>
		</button>

		{#if showManageRecurring}
			<div class="space-y-1.5 rounded-lg border border-[#1e1e2e] bg-[#0c0c0f] p-3">
				<!-- Existing recurring templates -->
				{#each data.recurringTemplates as tmpl}
					{@const tmplArea = tmpl.area ? areaFor(tmpl.area, data.areas) : null}
					{@const tmplColors = tmplArea ? colorClasses(tmplArea.color) : null}
					<div class="flex items-center gap-2 rounded border border-[#1e1e2e] bg-[#161620] px-2.5 py-2">
						<div class="flex-1 min-w-0">
							<span class="font-mono text-xs text-[#e2e2e8]">{tmpl.title}</span>
							<span class="ml-2 font-mono text-[10px] text-[#6b6b7a]">{tmpl.startsTime}</span>
							{#if tmplArea && tmplColors}
								<span class="ml-1 font-mono text-[9px] uppercase {tmplColors.text}">{tmplArea.label}</span>
							{/if}
							<p class="font-mono text-[9px] text-[#3a3a4e]">{tmpl.recurrenceDays.join(', ')}</p>
						</div>
						<form method="POST" action="?/deleteRecurringEvent" use:enhance>
							<input type="hidden" name="id" value={tmpl.id} />
							<button type="submit" class="font-mono text-[10px] text-[#3a3a4e] hover:text-red-400">✕</button>
						</form>
					</div>
				{/each}

				{#if data.recurringTemplates.length === 0 && !showAddRecurring}
					<p class="font-mono text-[10px] text-[#3a3a4e]">No recurring events yet</p>
				{/if}

				<!-- Toggle add form -->
				{#if !showAddRecurring}
					<button
						onclick={() => (showAddRecurring = true)}
						class="flex items-center gap-1.5 font-mono text-[10px] text-[#3a3a4e] transition-colors hover:text-[#6b6b7a]"
					>
						<span class="text-sm leading-none">+</span> Add recurring event
					</button>
				{:else}
					<!-- Add recurring event form -->
					<form
						method="POST"
						action="?/addRecurringEvent"
						use:enhance={() => {
							return async ({ update }) => {
								await update();
								showAddRecurring = false;
								newRecurringDays = [];
							};
						}}
						class="space-y-2 border-t border-[#1e1e2e] pt-2"
					>
						<input
							name="title"
							required
							placeholder="Event title..."
							class="w-full bg-transparent font-mono text-xs text-[#e2e2e8] placeholder-[#3a3a4e] outline-none"
						/>
						<div class="flex items-center gap-2">
							<input
								type="time"
								name="startsTime"
								required
								class="rounded border border-[#1e1e2e] bg-[#161620] px-2 py-1 font-mono text-xs
								       text-[#e2e2e8] outline-none [color-scheme:dark]"
							/>
							<span class="font-mono text-[10px] text-[#3a3a4e]">→</span>
							<input
								type="time"
								name="endsTime"
								class="rounded border border-[#1e1e2e] bg-[#161620] px-2 py-1 font-mono text-xs
								       text-[#e2e2e8] outline-none [color-scheme:dark]"
							/>
							<select
								name="area"
								class="rounded border border-[#1e1e2e] bg-[#161620] px-2 py-1 font-mono text-xs text-[#e2e2e8] outline-none"
							>
								<option value="">No area</option>
								{#each data.areas.filter(a => !a.suspended) as area}
									<option value={area.key}>{area.emoji} {area.label}</option>
								{/each}
							</select>
						</div>
						<!-- Day selector — checkboxes for each weekday -->
						<div class="flex flex-wrap gap-1">
							{#each WEEKDAYS as day}
								<label class="flex cursor-pointer items-center gap-1">
									<input
										type="checkbox"
										name="recurrenceDays"
										value={day}
										checked={newRecurringDays.includes(day)}
										onchange={(e) => {
											if (e.currentTarget.checked) {
												newRecurringDays = [...newRecurringDays, day];
											} else {
												newRecurringDays = newRecurringDays.filter(d => d !== day);
											}
										}}
										class="accent-violet-500"
									/>
									<span class="font-mono text-[10px] text-[#6b6b7a]">{day}</span>
								</label>
							{/each}
						</div>
						<div class="flex items-center gap-2">
							<button
								type="submit"
								class="rounded bg-violet-500/20 px-3 py-1 font-mono text-xs text-violet-400 hover:bg-violet-500/30"
							>
								Save
							</button>
							<button
								type="button"
								onclick={() => { showAddRecurring = false; newRecurringDays = []; }}
								class="font-mono text-xs text-[#3a3a4e] hover:text-[#6b6b7a]"
							>
								Cancel
							</button>
						</div>
					</form>
				{/if}
			</div>
		{/if}
	</div>

	<!-- ── Carry Forward ────────────────────────────────────────────────────── -->
	<!--
		Shows yesterday's incomplete tasks as suggestions.
		User can move them to today (carryForward) or dismiss them (dismissCarried).
		Hidden when there's nothing to carry forward.
	-->
	{#if data.carriedTasks.length > 0}
		<div class="rounded-lg border border-amber-500/20 bg-amber-500/5 p-3 space-y-2">
			<!-- Header -->
			<div class="flex items-center justify-between">
				<div class="flex items-center gap-2">
					<!-- Clock icon -->
					<svg width="11" height="11" viewBox="0 0 11 11" fill="none" class="text-amber-400/70">
						<circle cx="5.5" cy="5.5" r="4.5" stroke="currentColor" stroke-width="1.2"/>
						<path d="M5.5 3V5.5L7 6.5" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"/>
					</svg>
					<span class="font-mono text-[10px] font-semibold uppercase tracking-[0.12em] text-amber-400/70">
						From Yesterday ({data.carriedTasks.length})
					</span>
				</div>

				<!-- Carry all button -->
				<form method="POST" action="?/carryAll" use:enhance>
					<input type="hidden" name="todayDayId" value={data.day.id} />
					{#each data.carriedTasks as task}
						<input type="hidden" name="taskId" value={task.id} />
					{/each}
					<button
						type="submit"
						class="font-mono text-[10px] text-amber-400/60 transition-colors hover:text-amber-400"
					>
						Move all →
					</button>
				</form>
			</div>

			<!-- Per-task rows -->
			{#each data.carriedTasks as task}
				{@const taskArea = task.area ? areaFor(task.area, data.areas) : null}
				{@const taskColors = taskArea ? colorClasses(taskArea.color) : null}
				<div class="flex items-center gap-2 rounded border border-[#1e1e2e] bg-[#0c0c0f] px-2.5 py-2">
					<!-- Task text -->
					<span class="flex-1 font-mono text-xs text-[#c8c8d4]">{task.text}</span>
					<!-- Area badge -->
					{#if taskArea && taskColors}
						<span class="shrink-0 font-mono text-[9px] uppercase tracking-wider {taskColors.text}">
							{taskArea.label}
						</span>
					{/if}
					<!-- Carry forward -->
					<form method="POST" action="?/carryForward" use:enhance class="shrink-0">
						<input type="hidden" name="taskId" value={task.id} />
						<input type="hidden" name="todayDayId" value={data.day.id} />
						<button
							type="submit"
							title="Move to today"
							class="font-mono text-[10px] text-[#6b6b7a] transition-colors hover:text-amber-400"
						>
							→ Today
						</button>
					</form>
					<!-- Dismiss -->
					<form method="POST" action="?/dismissCarried" use:enhance class="shrink-0">
						<input type="hidden" name="taskId" value={task.id} />
						<button
							type="submit"
							title="Dismiss"
							class="font-mono text-[10px] text-[#3a3a4e] transition-colors hover:text-red-400"
						>
							✕
						</button>
					</form>
				</div>
			{/each}
		</div>
	{/if}

	<!-- ── Active Tasks ─────────────────────────────────────────────────────── -->
	<div class="space-y-1">
		<!-- Header row -->
		<div class="flex items-center justify-between py-1">
			<span class="font-mono text-[10px] font-semibold uppercase tracking-[0.12em] text-[#6b6b7a]">
				Active Tasks
			</span>
			{#if pendingTasks.length > 0}
				<span class="rounded bg-[#1e1e2e] px-1.5 py-0.5 font-mono text-[9px] text-[#6b6b7a]">
					{pendingTasks.length} Pending
				</span>
			{/if}
		</div>

		<!-- Pending tasks -->
		{#each pendingTasks as task}
			{@const taskArea = task.area ? areaFor(task.area, data.areas) : null}
			{@const taskColors = taskArea ? colorClasses(taskArea.color) : null}
			<div
				class="group flex items-center gap-2.5 rounded-lg border border-[#1e1e2e] bg-[#161620] px-3 py-3
					   transition-colors hover:border-[#2a2a3e]"
			>
				<!-- Drag handle (visual only) -->
				<span class="shrink-0 cursor-grab text-[#2a2a3e] transition-colors group-hover:text-[#3a3a4e]"
					  style="font-size: 11px; line-height: 1; letter-spacing: -1px;">⠿</span>
				<!-- Checkbox -->
				<form method="POST" action="?/toggleTask" use:enhance class="shrink-0">
					<input type="hidden" name="id" value={task.id} />
					<input type="hidden" name="done" value={String(task.done)} />
					<button
						type="submit"
						aria-label="Mark as done"
						class="h-4 w-4 rounded border-2 border-[#3e3e4e] transition-colors hover:border-violet-500"
					></button>
				</form>
				<!-- Task content -->
				<div class="flex min-w-0 flex-1 flex-col gap-0.5">
					<div class="flex items-center gap-1.5">
						<span class="font-mono text-sm text-[#e2e2e8]">{task.text}</span>
						<!-- Urgent dot -->
						{#if task.priority === 'urgent'}
							<span class="h-1.5 w-1.5 shrink-0 rounded-full bg-red-500"></span>
						{/if}
					</div>
					<!-- Area label + estimate row -->
					<div class="flex items-center gap-2">
						{#if taskArea && taskColors}
							<span class="font-mono text-[9px] uppercase tracking-wider {taskColors.text}">
								{taskArea.label}
							</span>
						{/if}
						{#if task.estimatedMinutes}
							<span class="flex items-center gap-1 font-mono text-[9px] text-[#3a3a4e]">
								<svg width="8" height="8" viewBox="0 0 8 8" fill="none">
									<circle cx="4" cy="4" r="3" stroke="currentColor" stroke-width="1"/>
									<path d="M4 2.5V4L5 5" stroke="currentColor" stroke-width="1" stroke-linecap="round"/>
								</svg>
								{task.estimatedMinutes}m
							</span>
						{/if}
					</div>
				</div>
				<!-- Delete -->
				<form method="POST" action="?/deleteTask" use:enhance class="shrink-0">
					<input type="hidden" name="id" value={task.id} />
					<button
						type="submit"
						class="font-mono text-[10px] text-[#2a2a3e] opacity-0 transition-all
							   group-hover:opacity-100 hover:text-red-400"
					>
						✕
					</button>
				</form>
			</div>
		{/each}

		<!-- Add task form -->
		<form
			method="POST"
			action="?/addTask"
			use:enhance={() => {
				return async ({ update }) => {
					await update();
					newTaskText = '';
				};
			}}
			class="flex items-center gap-2 rounded-lg border border-dashed border-[#1e1e2e] bg-transparent
				   px-3 py-2.5 transition-colors hover:border-[#2a2a3e]"
		>
			<input type="hidden" name="dayId" value={data.day.id} />
			<span class="font-mono text-sm text-[#3e3e4e]">+</span>
			<input
				bind:value={newTaskText}
				name="text"
				required
				placeholder="Add a task..."
				class="flex-1 bg-transparent font-mono text-sm text-[#e2e2e8] placeholder-[#3e3e4e] outline-none"
			/>
			<select
				bind:value={newTaskArea}
				name="area"
				class="rounded border border-[#1e1e2e] bg-[#0c0c0f] px-2 py-1 font-mono text-xs text-[#e2e2e8] outline-none"
			>
				<option value="">No area</option>
				{#each data.areas.filter(a => !a.suspended) as area}
					<option value={area.key}>{area.emoji} {area.label}</option>
				{/each}
			</select>
		</form>

		<!-- Show completed row -->
		{#if doneTasks.length > 0}
			<details class="group">
				<summary
					class="flex cursor-pointer list-none items-center gap-1.5 py-2 font-mono text-[10px]
						   uppercase tracking-[0.08em] text-[#3a3a4e] transition-colors hover:text-[#6b6b7a]"
				>
					<span class="inline-block transition-transform group-open:rotate-90">›</span>
					Show Completed ({doneTasks.length})
				</summary>
				<div class="mt-1 space-y-1">
					{#each doneTasks as task}
						{@const taskArea = task.area ? areaFor(task.area, data.areas) : null}
						{@const taskColors = taskArea ? colorClasses(taskArea.color) : null}
						<div
							class="flex items-center gap-2.5 rounded-lg border border-[#1e1e2e]/50 bg-[#161620]/50 px-3 py-2.5"
						>
							<form method="POST" action="?/toggleTask" use:enhance class="shrink-0">
								<input type="hidden" name="id" value={task.id} />
								<input type="hidden" name="done" value={String(task.done)} />
								<button
									type="submit"
									class="flex h-4 w-4 items-center justify-center rounded border-2
										   border-green-500/50 bg-green-500/10"
								>
									<svg viewBox="0 0 12 12" fill="none" class="h-2.5 w-2.5">
										<path d="M2 6l3 3 5-5" stroke="rgb(74 222 128)" stroke-width="1.5"
											  stroke-linecap="round" stroke-linejoin="round"/>
									</svg>
								</button>
							</form>
							<span class="flex-1 font-mono text-sm text-[#6b6b7a] line-through">{task.text}</span>
							{#if taskArea && taskColors}
								<span class="font-mono text-[9px] uppercase tracking-wider opacity-50 {taskColors.text}">
									{taskArea.label}
								</span>
							{/if}
							<form method="POST" action="?/deleteTask" use:enhance class="shrink-0">
								<input type="hidden" name="id" value={task.id} />
								<button type="submit" class="font-mono text-[10px] text-[#3e3e4e] hover:text-red-400">✕</button>
							</form>
						</div>
					{/each}
				</div>
			</details>
		{/if}
	</div>

	<!-- ── Brain Dump / Inbox ─────────────────────────────────────────────────── -->
	<!-- Quick capture for anything on your mind — not tied to a specific time or task -->
	<div class="hidden lg:block space-y-2">
		<span class="font-mono text-[10px] font-semibold uppercase tracking-[0.12em] text-[#6b6b7a]">
			Brain Dump
		</span>

		<!-- Capture form — pressing Enter submits -->
		<form
			method="POST"
			action="?/addInboxItem"
			use:enhance={() => {
				return async ({ update }) => {
					await update();
					newInboxText = '';
				};
			}}
			class="flex items-center gap-2 rounded-lg border border-[#1e1e2e] bg-[#161620] px-3 py-2.5"
		>
			<span class="font-mono text-[#3e3e4e]">⚡</span>
			<input
				bind:value={newInboxText}
				name="text"
				placeholder="Dump it out..."
				class="flex-1 bg-transparent font-mono text-sm text-[#e2e2e8] placeholder-[#3e3e4e] outline-none"
			/>
		</form>

		{#each data.inboxItems as item}
			<div
				class="flex items-center gap-2 rounded-lg border border-[#1e1e2e] bg-[#161620] px-3 py-2"
			>
				<span class="flex-1 font-mono text-sm text-[#e2e2e8]">{item.text}</span>

				<!-- Convert inbox item to a task for today -->
				<form method="POST" action="?/convertInboxToTask" use:enhance>
					<input type="hidden" name="itemId" value={item.id} />
					<input type="hidden" name="text" value={item.text} />
					<input type="hidden" name="dayId" value={data.day.id} />
					<button
						type="submit"
						title="Convert to task"
						class="px-1 font-mono text-xs text-[#6b6b7a] transition-colors hover:text-violet-400"
					>
						→ task
					</button>
				</form>

				<form method="POST" action="?/deleteInboxItem" use:enhance>
					<input type="hidden" name="id" value={item.id} />
					<button
						type="submit"
						class="font-mono text-xs text-[#3e3e4e] transition-colors hover:text-red-400"
					>
						✕
					</button>
				</form>
			</div>
		{/each}
	</div>
  {/snippet}

  {#snippet panel()}
    <!-- ── Current Capacity (Energy Picker) ─────────────────────────────────── -->
    <PanelCard title="Current Capacity">
      <!-- 2×2 grid of energy states -->
      <div class="grid grid-cols-2 gap-2">
        {#each ENERGY_LEVELS as level}
          <form method="POST" action="?/setEnergy" use:enhance>
            <input type="hidden" name="dayId" value={data.day.id} />
            <input type="hidden" name="energy" value={level.key} />
            <button
              type="submit"
              class="w-full rounded-lg p-3 text-center transition-all
                     {data.day.energy === level.key
                       ? 'bg-[#1e1e2e] ring-1 ring-violet-500/50'
                       : 'bg-[#0c0c0f] hover:bg-[#161620]'}"
            >
              <div class="mb-1 text-lg">{level.emoji}</div>
              <div class="font-mono text-[9px] uppercase tracking-widest
                          {data.day.energy === level.key ? 'text-violet-400' : 'text-[#6b6b7a]'}">
                {level.label}
              </div>
            </button>
          </form>
        {/each}
      </div>
    </PanelCard>

    <!-- ── MVD Goal ──────────────────────────────────────────────────────────── -->
    <div class="rounded-xl border-l-4 border-amber-500/60 bg-[#161620] px-4 py-3">
      <form method="POST" action="?/toggleMvd" use:enhance class="flex items-start gap-3">
        <input type="hidden" name="dayId" value={data.day.id} />
        <input type="hidden" name="current" value={String(data.day.mvdDone)} />
        <button
          type="submit"
          class="mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded border-2 transition-colors
                 {data.day.mvdDone
                   ? 'border-amber-500 bg-amber-500/20'
                   : 'border-[#3e3e4e] hover:border-amber-500'}"
        >
          {#if data.day.mvdDone}
            <svg viewBox="0 0 12 12" fill="none" class="h-2.5 w-2.5">
              <path d="M2 6l3 3 5-5" stroke="rgb(251 191 36)" stroke-width="1.5"
                    stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
          {/if}
        </button>
        <div>
          <p class="font-mono text-[9px] font-semibold uppercase tracking-[0.12em] text-amber-500/70">
            MVD Goal
          </p>
          <p class="mt-0.5 font-mono text-sm {data.day.mvdDone ? 'text-[#6b6b7a] line-through' : 'text-[#e2e2e8]'}">
            {mvdHint}
          </p>
        </div>
      </form>
    </div>

    <!-- ── Pomodoro Timer ────────────────────────────────────────────────────── -->
    <div id="pomodoro-panel">
      <PomodoroTimer dayId={data.day.id} sessions={data.day.pomodoroSessions} tasks={pendingTasks} />
    </div>

    <!-- ── Daily Note ────────────────────────────────────────────────────────── -->
    <PanelCard title="Daily Note">
      <form method="POST" action="?/updateNote" use:enhance>
        <input type="hidden" name="dayId" value={data.day.id} />
        <textarea
          name="note"
          placeholder="Capturing thoughts, ideas, and reflections for later..."
          onblur={(e) => e.currentTarget.form?.requestSubmit()}
          class="min-h-[80px] w-full resize-none bg-transparent font-mono text-xs
                 leading-relaxed text-[#c8c8d4] placeholder-[#3a3a4e] outline-none"
        >{data.day.note}</textarea>
      </form>
    </PanelCard>

    <!-- ── Sleep Logging ─────────────────────────────────────────────────────── -->
    <!--
      Two time inputs: bed time (treated as yesterday) + wake time (today).
      Autosaves on blur — same pattern as Daily Note.
      Duration is computed client-side for instant feedback; the form persists to DB.
    -->
    <PanelCard title="Sleep">
      <form
        method="POST"
        action="?/logSleep"
        use:enhance
        class="space-y-3"
      >
        <input type="hidden" name="dayId" value={data.day.id} />

        <div class="grid grid-cols-2 gap-2">
          <!-- Bed time — the night before -->
          <div class="space-y-1">
            <label for="bedTime" class="font-mono text-[9px] uppercase tracking-wider text-[#3a3a4e]">
              Went to bed
            </label>
            <input
              id="bedTime"
              type="time"
              name="bedTime"
              bind:value={bedTime}
              onblur={(e) => e.currentTarget.form?.requestSubmit()}
              class="w-full rounded border border-[#1e1e2e] bg-[#0c0c0f] px-2 py-1.5
                     font-mono text-xs text-[#e2e2e8] outline-none
                     focus:border-[#2a2a3e] [color-scheme:dark]"
            />
          </div>

          <!-- Wake time — this morning -->
          <div class="space-y-1">
            <label for="wakeTime" class="font-mono text-[9px] uppercase tracking-wider text-[#3a3a4e]">
              Woke up
            </label>
            <input
              id="wakeTime"
              type="time"
              name="wakeTime"
              bind:value={wakeTime}
              onblur={(e) => e.currentTarget.form?.requestSubmit()}
              class="w-full rounded border border-[#1e1e2e] bg-[#0c0c0f] px-2 py-1.5
                     font-mono text-xs text-[#e2e2e8] outline-none
                     focus:border-[#2a2a3e] [color-scheme:dark]"
            />
          </div>
        </div>

        <!-- Sleep duration — shown once both fields are filled -->
        {#if sleepDuration()}
          {@const d = sleepDuration()!}
          {@const color = d.hours < 6 ? 'text-red-400' : d.hours < 7 ? 'text-amber-400' : 'text-green-400'}
          <p class="font-mono text-xs {color}">
            {d.hours}h {d.mins > 0 ? `${d.mins}m` : ''} sleep
            {#if d.hours < 6}
              · under 6h impacts focus
            {:else if d.hours >= 8}
              · optimal
            {/if}
          </p>
        {:else}
          <p class="font-mono text-[10px] text-[#3a3a4e]">Log sleep to see patterns in Stats</p>
        {/if}
      </form>
    </PanelCard>
  {/snippet}
</TwoColumnPage>

<!-- ── Mobile Quick Capture Bar ─────────────────────────────────────────── -->
<!-- Fixed above the mobile bottom nav. Desktop: hidden (Brain Dump section handles it). -->
<div
  class="lg:hidden fixed left-0 right-0 z-30 border-t border-[#1e1e2e] bg-[#12121c]/95 px-4 py-2 backdrop-blur-sm"
  style="bottom: calc(4rem + env(safe-area-inset-bottom))"
>
  <form
    method="POST"
    action="?/addInboxItem"
    use:enhance={() => {
      return async ({ update }) => {
        await update();
        newInboxText = '';
      };
    }}
    class="flex items-center gap-2 rounded-lg border border-[#1e1e2e] bg-[#161620] px-3 py-2"
  >
    <!-- Capture icon -->
    <svg width="12" height="12" viewBox="0 0 12 12" fill="none" class="shrink-0 text-[#3a3a4e]">
      <rect x="1" y="1" width="10" height="10" rx="1.5" stroke="currentColor" stroke-width="1.2"/>
      <path d="M4 6H8M6 4V8" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"/>
    </svg>
    <input
      bind:value={newInboxText}
      name="text"
      placeholder="Quick capture brain dump..."
      class="flex-1 bg-transparent font-mono text-sm text-[#e2e2e8] placeholder-[#3a3a4e] outline-none"
    />
    <!-- Task icon button -->
    <button
      type="submit"
      name="captureType"
      value="inbox"
      class="shrink-0 text-[#3a3a4e] transition-colors hover:text-[#6b6b7a]"
      aria-label="Save to inbox"
    >
      <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
        <circle cx="7" cy="7" r="5.5" stroke="currentColor" stroke-width="1.2"/>
        <path d="M4.5 7L6.5 9L9.5 5" stroke="currentColor" stroke-width="1.2"
              stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    </button>
  </form>
</div>
